# Generated by Django 4.1.1 on 2022-09-17 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="status",
            field=models.IntegerField(choices=[(1, "Available"), (0, "Unavailable")]),
        ),
    ]
