# Generated by Django 4.1.1 on 2022-09-17 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0002_alter_course_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="register",
            name="course",
        ),
        migrations.CreateModel(
            name="user_quotas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount_taken", models.IntegerField(default=1)),
                (
                    "course",
                    models.ManyToManyField(
                        blank=True, related_name="user_quota", to="registrar.course"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usequota",
                        to="registrar.student",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="register",
            name="course",
            field=models.ManyToManyField(
                blank=True, related_name="course", to="registrar.course"
            ),
        ),
    ]
