# Generated by Django 4.1.1 on 2022-09-18 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("registrar", "0003_remove_register_course_user_quotas_register_course"),
    ]

    operations = [
        migrations.AlterField(
            model_name="register",
            name="course",
            field=models.ManyToManyField(
                blank=True, related_name="rg_course", to="registrar.course"
            ),
        ),
        migrations.AlterField(
            model_name="register",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rg_student",
                to="registrar.student",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="username",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="user_quotas",
        ),
    ]
