name: Testing
on: push

jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Django unit tests
      run: |
        pip3 install -r reg/requirements.txt
        python3 reg/manage.py makemigrations
        python3 reg/manage.py migrate
        coverage run --source='.' reg/manage.py test
        coverage report
